### ISSUE TITLE
OldMessages theme no longer fully works 

### ISSUE THREAD

**Issue by kuzlan** [PseudoResonance/BetterDiscord-Theme#2]
It doesn't stop discord from highlighting messages when hovering and the lines between messages don't work anymore.
I really dislike what discord did, could u please update this, really like ur discord theme, been using it since discord updated.

**Comment by EmeraldSnorlax** [comment]
I am also having this issue. Reinstalling with betterdiscordctl does nothing.

```
Stable 65349 (99df168)
BBD 0.3.5
Host 0.0.11
Injector 0.6.2
Linux 64-Bit (5.7.12-Arch1-1)
Old Messages Version: V1.1.10
```

**Comment by EmeraldSnorlax** [comment]
@kuzlan I found an alternative theme that still works https://github.com/fluffingtons/revert-discord

**Comment by RavenousSix** [comment]
Yes please, would love an update to this. It used to work through every patch except today. Now it's fully broken.

**Comment by RavenousSix** [comment]
> 
> 
> @kuzlan I found an alternative theme that still works https://github.com/fluffingtons/revert-discord

Thank you so much! This works as of August 15 2020. Much appreciated.

**Comment by PseudoResonance** [comment]
The issue should be fixed anyways now. They just changed the messages class for some reason.
