### ISSUE TITLE
URLDecode doesn't work

### ISSUE THREAD

**Issue by gcobc12632** [PseudoResonance/BetterDiscord-Theme#6]
I tried posting a link on discord

ex: https://zh.wikipedia.org/wiki/%E7%B6%B2%E9%A0%81

and it shows:
![](https://i.imgur.com/47dwD4x.png)

seems doesn't work

**Comment by PseudoResonance** [comment]
Sorry, with the Discord changes it has become harder to make plugins and I have been busy recently. Hopefully I will be able to fix it soon.

**Comment by PseudoResonance** [comment]
Fixed in version 2.0.0 commit [01632a9](https://github.com/PseudoResonance/BetterDiscord-Theme/commit/01632a9c44b9141f85c2cf393dfac8df0c662eab).
